### ISSUE TITLE
Output Interpretation/Documentation

### ISSUE THREAD

**Issue by apblair** [ecolell/amphipathic#2]
Hello,
Thanks for developing this user-friendly tool. I'm writing to ask how I can interpret the output. For example, do you have documentation for the output dictionary keys 'type', 'index', and 'mean'?
Thanks,
Andrew

**Comment by ecolell** [comment]
Hello @apblair,

I've updated the README with some information. I've contacted Ghiringhelli for details about the index algorithm it self.
I'll be linking any new information into this thread.

**Comment by ecolell** [comment]
@apblair I've extended the README with some information provided by Ghiringhelli. If you think the README is extensive enough, please close this issue.

If you find this tool could be improved in any other way, please feel free to create more issues! or let's join forces!

**Comment by ecolell** [comment]
I'm closing this issue since it looks solved. Please reopen if considered required.
